name: build
on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login To Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build And Push Docker Images
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          push: true
          tags: mstiesto/bonbast:latest

      - name: Docker Compose Remote Deployment
        uses: astappiev/docker-compose-remote-action@master
        with:
          ssh_host: ${{ secrets.REMOTE_ADDRESS }}
          ssh_user: ${{ secrets.REMOTE_USERNAME }}
          ssh_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          ssh_host_public_key: ${{ secrets.REMOTE_PUBLIC_KEY }}
          docker_compose_prefix: bonbast