name: build
on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login To Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build And Push Docker Images
        uses: docker/build-push-action@v4.0.0
        with:
          build-args: BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          push: true
          tags: mstiesto/bonbast:latest

      - name: Deploy Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_ADDRESS }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd /srv/bonbast/
            sudo /usr/bin/docker compose restart bonbast